//
//  UIColor+TMPAdditions.swift
//
//  Generated by Zeplin on 6/11/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class func tmpGreyd5Color() -> UIColor {
		return UIColor(white: 213.0 / 255.0, alpha: 1.0)
	}

	class func tmpGrey7DColor() -> UIColor {
		return UIColor(white: 125.0 / 255.0, alpha: 1.0)
	}

	class func tmpGreyd1Color() -> UIColor {
		return UIColor(white: 209.0 / 255.0, alpha: 1.0)
	}

	class func tmpGrey30AColor() -> UIColor {
		return UIColor(white: 0.0, alpha: 0.3)
	}

	class func tmpWhiteColor() -> UIColor {
		return UIColor(white: 255.0 / 255.0, alpha: 1.0)
	}
}
